spring:
  profiles:
    active:
    - dev  #开发环境
   
  #时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
      
#redis
  redis:
    database: 0
    host: 192.168.0.109
    port: 6379
    password: 
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000

#mybatis
mybatis:
  mapper-locations:
  - classpath:mapper/*/*.xml
#  type-aliases-package: com.lichi.increaselimit
  configuration:
    mapUnderscoreToCamelCase: true   #自动驼峰转换
    useColumnLabel: true

#通用mapper
mapper:
    mappers:
        - com.lichi.increaselimit.common.mapper.BaseMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
    
    
    
lichi:
#验证码配置
  code:
    image:
      height: 23
      width: 67
    sms:
      expire-in: 60
      url: 
      length: 6
      
#oauth2.0安全认证的参数
  oauth2-properties:
    clients:
    - client-id: lichi
      client-secret: 123456
      access-token-validity-seconds: 7200
      grant-types:
      - password, refresh_token,implicit
      scopes:
      - all, read, write
    jwt-signing-key: lichi
    storeType: jwt   #token的存放方式
    
  #第三方登陆
  social:
    qq:
      provider-id: 
      app-id: 
      app-secret:  
      providerId: callback.do
    weixin:
       app-id: wxd99431bbff8305a0
       app-secret: 60f78681d063590a469f1b297feff3c4
    filterProcessesUrl: /qqLogin

