spring:
  profiles:
    active:
    - dev  #开发环境
   
  #时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
      
#redis
  redis:
    database: 0
    host: 192.168.0.109
    port: 6379
    password: 
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000

  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: 
      max-file-size: 1MB
      max-request-size: 10Mb
      
#mybatis
mybatis:
  mapper-locations:
  - classpath:mapper/*/*.xml
#  type-aliases-package: com.lichi.increaselimit
  configuration:
    mapUnderscoreToCamelCase: true   #自动驼峰转换
    useColumnLabel: true

#通用mapper
mapper:
    mappers:
        - com.lichi.increaselimit.common.mapper.BaseMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
    
    
    
lichi:
#验证码配置
  code:
    image:
      height: 23
      width: 67
    sms:
      expire-in: 900
      url: 
      length: 6
    
  #第三方登陆
  social:
    qq:
      provider-id: 
      app-id: 
      app-secret:  
      providerId: qq
    weixin:
       app-id: wxd99431bbff8305a0
       app-secret: 60f78681d063590a469f1b297feff3c4
    filterProcessesUrl: /qqLogin


logging:
  config: 
  - classpath:logback-lichi.xml
  
